#!/bin/sh
pushd build
cmake -DCMAKE_BUILD_TYPE=Release ..
if [ $? -eq 0 ]; then
    popd
    cmake --build build
    if [ $? -eq 0 ]; then
        ./build/linux/kettlevm
    else
        exit 1
    fi
else
    exit 1
fi
